const SHORT_MOVIE_DURATION = 40;

const VISIBLE_MOVIES_MOBILE = 5;
const MOVIES_TO_LOAD_MOBILE = 2;
const VISIBLE_MOVIES_TABLET = 8;
const MOVIES_TO_LOAD_TABLET = 2;
const VISIBLE_MOVIES_DESKTOP = 16;
const MOVIES_TO_LOAD_DESKTOP = 4;

export {
  SHORT_MOVIE_DURATION,
  VISIBLE_MOVIES_MOBILE,
  MOVIES_TO_LOAD_MOBILE,
  VISIBLE_MOVIES_TABLET,
  MOVIES_TO_LOAD_TABLET,
  VISIBLE_MOVIES_DESKTOP,
  MOVIES_TO_LOAD_DESKTOP
};